### PR TITLE
Handle errors when calling slack - BEHROUZ - #26

### LINKED ISSUE #26: Handle errors when calling Slack
This ticket covers what happens when Slack returns an error to the [lookupByEmail](https://api.slack.com/methods/users.lookupByEmail) call.

We should return an appropriate response code based on the type of error:

No user found? 404
Other error? 500

Depends on #25 & #24

### PR DESCRIPTION
**Pull request by bkarimii**
## Description

Endpoint developed to handle errors based on the response received from Slack, e.g., returning a 404 for not found users and a 500 for server errors.

## Related to

Fixes #26

### CODE REVIEW

**Review by oliverlloyd — COMMENTED** [review]
This work is dependant on #25 so we can't work on this until that is done

Do you see how this PR contains both the code for #25, the business logic to make the call, and also the code for handling the response? It's duplicated between the two.

You need to wait for the first piece of work to be completed, reviewed and merged and then you can do the next step.

File: web/src/pages/Home.jsx [hunk 1]
```diff
@@ -4,6 +4,8 @@ function App() {
 	return (
 		<>
 			<h1>CYF Slack Dashboard</h1>
+			<h2>Apples</h2>
+			<h3>Bananas</h3>
```
Comment (oliverlloyd) [inline web/src/pages/Home.jsx]: I think these changes slipped in unintentionally :)

**Review by oliverlloyd — APPROVED** [review]
